# Generated by Django 3.2.5 on 2021-07-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contact Name', max_length=50)),
                ('email', models.EmailField(help_text='Contact Email', max_length=50)),
                ('phone', models.PositiveIntegerField(help_text='Phone Number')),
                ('info', models.TextField(blank=True, max_length=200)),
                ('gender', models.CharField(help_text='contact Gender', max_length=2)),
                ('image', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
