# Generated by Django 3.2.5 on 2021-07-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(help_text='contact Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.TextField(blank=True, help_text='Contact Description', max_length=200),
        ),
    ]
