# Generated by Django 3.2.5 on 2021-07-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(help_text='Contact Image', upload_to='static/images'),
        ),
    ]
