# Generated by Django 3.2.5 on 2021-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.CharField(blank=True, help_text='Contact Relationship', max_length=50),
        ),
    ]
