# Generated by Django 3.2.5 on 2021-07-14 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_alter_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.CharField(blank=True, help_text='About the contact', max_length=50),
        ),
    ]
