# Generated by Django 3.2.5 on 2021-07-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20210718_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id']},
        ),
    ]
